const SUPABASE_URL = 'https://jrjriwnjjpykijlgrbba.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyanJpd25qanB5a2lqbGdyYmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NzEyMzYsImV4cCI6MjA5OTU0NzIzNn0.md5t3d1S6bRqEt4TntH04iX3DAhQBuOTXARF-_IEpeg';
